sudo: false
dist: trusty

language: go

matrix:
  include:
  - go: 1.7.6
  - go: 1.8.5
  - go: 1.9.2

install:
  - # Do nothing.

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
